### ISSUE TITLE
Getting a deeper understanding

### ISSUE THREAD

**Issue by jyhong05** [nathan-create/simulation#8]
I couldn't help but notice that your hodgkin huxley code was exactly the same as mine, down to the in-line comments and spacing. I recommend you try to actually do the model problem to gain an understanding of what the model actually is and represents.

**Comment by nathan-create** [comment]
I reverted to an older version of my repository, and redid the model from the beginning. I apologize.

**Comment by nathan-create** [comment]
I reverted to an older version of my repository and redid the model from the beginning. I apologize.
